spring:
  h2:
    console:
      enabled: true


  datasource:
    url: jdbc:h2:mem:beanfood
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5